version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: feedpulse
      POSTGRES_PASSWORD: feedpulse
      POSTGRES_DB: feedpulse
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
  api:
    build: ./api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  worker:
    build: ./worker
    volumes:
      - .:/app
    depends_on:
      - api
      - redis
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api
volumes:
  pgdata:
